### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by FlorianUekermann** [FloopCZ/tensorflow_cc#132] opened 2018-08-14 16:12 UTC
It would be great if you could provide binary releases of the shared library with headers for linux and osx. Maybe just a minimal cpu-only config.

**Comment by FloopCZ** [comment] 2018-08-15 07:51
Hi, I am closing this as a duplicate of #8.

**Closed by FloopCZ** 2018-08-15 07:51 UTC

**Comment by FlorianUekermann** [comment] 2018-08-15 11:35
By "provide binary releases" I meant upload the resulting `.h` and `.so` files, not a `.deb` package or similar.

**Comment by FloopCZ** [comment] 2018-08-15 15:51
I understand, but there is no single `.h` file with the TensorFlow C++ API and the headers are scattered all over the place. If there was a simple location of headers and sources, there would be no reason for this project at all, but unfortunately, this is not the case. See e.g., https://github.com/tensorflow/tensorflow/issues/2412.

If #8 is resolved, we can generate not only `.deb` package, but also simple `.tar` with the resources you require (PR welcome).
