### ISSUE TITLE
Question: Docker image TensorFlow v1.9.0?

### ISSUE THREAD

**Issue by fakhamatia** [FloopCZ/tensorflow_cc#204] opened 2020-02-26 00:33 UTC
How can I download Docker image of TensorFlow v1.9.0?
The LAST PUSHED in Docker Hub is v1.15.0?

**Comment by FloopCZ** [comment] 2020-02-29 22:33
Hi, yes, sorry, there are no older images as of the moment. This has actually already been requested in #160, I just did not have enough time to change the scripts. You can clone the 1.9.0 version of this project and build it manually, but I am really not sure you will be able to compile v1.9.0 on up-to-date systems.

Closing as duplicate of #160.

**Closed by FloopCZ** 2020-02-29 22:33 UTC
