### ISSUE TITLE
opencv image read issure

### ISSUE THREAD

**Issue by Edwardmark** [FloopCZ/tensorflow_cc#29] opened 2017-11-08 13:35 UTC
I found that if I link tf package, then opencv cannot read image, is there any solution?

**Comment by FloopCZ** [comment] 2017-11-08 16:46
Hi, I believe that you encounter the same problem as #19, is it possible? What is the error message?

**Comment by FloopCZ** [comment] 2017-12-10 18:02
Closing as a duplicate of #19.

**Closed by FloopCZ** 2017-12-10 18:02 UTC
