### ISSUE TITLE
Error after download from bitbucket

### ISSUE THREAD

**Issue by Woodyet** [FloopCZ/tensorflow_cc#193] opened 2019-12-04 18:42 UTC
Hi,

I am having an issue when compiling using 

cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..

When I do make it starts and clones tensorflow but gets stuck after the following
 
[  6%] Performing configure step for 'tensorflow_base'
PROTOC = "protoc"
CC_PREFIX = ""
downloading https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
CMakeFiles/tensorflow_base.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_base-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_base-configure] Error 2
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_base.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_base.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I have followed the link to https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz and it goes nowhere.

I am aware bit-bucket had an upgrade recently is it to do with this?

Sorry if it is a basic fix

**Comment by Woodyet** [comment] 2019-12-04 18:43
Oh sorry just saw the post below!

**Comment by dtsmith2001** [comment] 2019-12-04 21:14
See #192

**Comment by FloopCZ** [comment] 2019-12-05 11:11
Closing as duplicate of #192, thank you for the report though.

**Closed by FloopCZ** 2019-12-05 11:11 UTC
