### ISSUE TITLE
Avoid illegal instructions on pre-haswell processors

### ISSUE THREAD

**Issue by fli** [FloopCZ/tensorflow_cc#89] opened 2018-04-28 16:02 UTC
https://github.com/FloopCZ/tensorflow_cc/blob/354b616d25234c33d14c39633cb31e40d443c6f6/tensorflow_cc/cmake/build_tensorflow.sh#L5

Maybe change this to `-march=native` so that tensorflow_cc runs on pre-haswell processors. Otherwise you get an `Illegal Instruction (core dumped)` error when running anything compiled with the library

**Comment by FloopCZ** [comment] 2018-04-28 17:12
Closing as duplicate of #76.

**Closed by FloopCZ** 2018-04-28 17:12 UTC
