### ISSUE TITLE
Building shared tensorflow_cc

### ISSUE THREAD

**Issue by rspezialetti** [FloopCZ/tensorflow_cc#23] opened 2017-09-26 10:48 UTC
I'm trying to build shared lib but i get this error: 
cp: cannot copy a directory, '/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf', into itself, './tensorflow/contrib/makefile/gen/protobuf/protobuf
CMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by FloopCZ** [comment] 2017-09-26 15:32
Hi, it seems that the library is trying to be installed to the current working directory. Have you used only `cmake ..` or have you used something as `cmake -DCMAKE_INSTALL_PREFIX=...` ?

**Comment by rspezialetti** [comment] 2017-09-26 15:55
Hi, i only used cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..

**Comment by FloopCZ** [comment] 2017-09-26 17:04
Strange, I am not really sure where this could happen. Can you tell me your operating system version (`uname -a`) and the exact sequence of commands you have done?

**Comment by rspezialetti** [comment] 2017-09-27 06:41
Output of uname -a : 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Commande sequence: cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON  ..
                                      make && sudo make install

**Comment by dmalkr** [comment] 2017-09-27 11:41
Also have this bug

**Comment by FloopCZ** [comment] 2017-09-27 22:43
I still do not know from where does the issue originate. :-( Can you try whether it also happens in the case of  building the static library?
(just `cmake ..`)
I will rebuild the [Dockerfile tests](https://github.com/FloopCZ/tensorflow_cc/tree/master/Dockerfiles) to find out whether it is not because of a new version of some package.

**Comment by FloopCZ** [comment] 2017-10-20 09:06
I have made some improvements to the library. Can you please make a clean clone of the project and try over? Beware that the list of requirements has slightly changed, now `g++-6` is used instead of `g++-5`, see the [README.md](https://github.com/FloopCZ/tensorflow_cc).

In the new version, all tests are green and TensorFlow 1.4.0-rc0 is used.

**Comment by sjdrc** [comment] 2017-10-21 03:54
I'm encountering this error after a clean clone and working through the issues in #27. I actually get a build failure and need to manually move a line in cuda/cuda_dnn.cc in order to get tensorflow to compile through bazel, but perhaps completing the build with an existing build folder is the issue here? I'll try editing one of your scripts to get the change to happen automatically.

**Comment by sjdrc** [comment] 2017-10-21 04:34
So the issue I have with cuda/cuda_dnn.cc is resolved by applying this fix https://github.com/tensorflow/tensorflow/pull/13255.

I added the line

```
	    COMMAND printf %s\\n 235m247 w q | ed -s tensorflow/stream_executor/cuda/cuda_dnn.cc
```

After the other COMMAND lines in tensorflow_cc/cmake/TensorflowBase.cmake.

**Comment by zhenglaizhang** [comment] 2017-11-04 13:34
Hi, have you solved the issue? currently I also met with the issue as below:
```
Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 14.921s, Critical Path: 5.78s
cp: cannot copy a directory, '/tmp/repo/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf', into itself, './tensorflow/contrib/makefile/gen/protobuf/protobuf'
make[2]: *** [CMakeFiles/tensorflow_shared.dir/build.make:112: tensorflow-stamp/tensorflow_shared-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/tensorflow_shared.dir/all] Error 2
```

**Comment by FloopCZ** [comment] 2017-11-05 10:27
Hi, I have not been able to reproduce the issue yet. It looks as if the CMake install prefix is set to the current working directory instead of `/usr/local`. Can you please try to configure the project using
```
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON -DCMAKE_INSTALL_PREFIX=/usr/local ..
```
That is, explicity setting the install prefix? Thanks.

**Comment by hyperdrive** [comment] 2017-11-13 19:05
@FloopCZ  Explicitly adding CMAKE_INSTALL_PREFIX solved the the "cannot copy a directory" on Ubuntu 16 for me.

**Comment by FloopCZ** [comment] 2017-11-20 23:17
@hyperdrive Thank you for the information, I will have to put this information to the `README.md`. I still wonder how is it possible that for some installations, the default cmake install prefix is set to the current workdir, though.

**Closed** 2017-12-10 18:23 UTC

**Comment by FloopCZ** [comment] 2017-12-11 08:37
I have finally found and fixed the real source of the issue in the latest master.
