### ISSUE TITLE
File system loop detected

### ISSUE THREAD

**Issue by achalshah20** [FloopCZ/tensorflow_cc#137] opened 2018-09-21 23:38 UTC
Is anyone getting following error? This went to infinite loop and protobuf is keep getting copied into protobuf folder.

```
Replacing links with the copies of their targets.
This may take a while...
find: File system loop detected; ‘./tensorflow/contrib/makefile/gen/protobuf/protobuf’ is part of the same file system loop as ‘./tensorflow/contrib/makefile/gen/protobuf’.
find: File system loop detected; ‘./tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf’ is part of the same file system loop as ‘./tensorflow/contrib/makefile/gen/protobuf-host/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/protobuf/protobuf/protobuf’.

```

**Comment by FloopCZ** [comment] 2018-11-16 20:35
Hi, this never happened to me, is this still happening to you? Do you have some special filesystem layout?

**Comment by achalshah20** [comment] 2018-11-21 02:33
It happens when your build is progress and you force terminate it and run cmake again. Something happening to protobuf link in this case and protobuf links to itself and goes to infinite loop while copying.

**Comment by FloopCZ** [comment] 2018-11-22 20:46
I see, this is a duplicate of #140. Strange things can happen when the build is terminated prematurely, I am not sure it is worth fixing though, since a clean rebuild should do the trick.

**Closed by FloopCZ** 2018-11-22 20:46 UTC
Labels: duplicate
