### ISSUE TITLE
No session factory registered 

### ISSUE THREAD

**Issue by WilliamTambellini** [FloopCZ/tensorflow_cc#62] opened 2018-03-02 23:54 UTC
Hi Filip
I followed the steps on the main page (static lib, cpu) but when running the exampe the execution failed : 

2018-03-02 15:49:15.631604: E tensorflow/core/common_runtime/session.cc:69] Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.
Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.

**Comment by achalshah20** [comment] 2018-03-03 01:40
May be a duplicate of #58

**Comment by FloopCZ** [comment] 2018-03-03 15:49
Hi @WilliamTambellini, it indeed seems to be a duplicate of #58. Can you please try #64, whether it solves your problem? Thanks.

**Comment by WilliamTambellini** [comment] 2018-03-04 19:58
Hi @FloopCZ   
I m using the static cpu build ie not bazel but makefile based.

**Comment by FloopCZ** [comment] 2018-03-11 19:21
Strange, I am unable to reproduce the issue. Have you tried the process from a clean working directory? (i.e., removed `tensorflow_cc/build` folder` ?

**Comment by FloopCZ** [comment] 2018-03-30 21:46
Closing for inactivity. There has been a lot of changes recently, feel free to reopen if the issue persists.

**Closed by FloopCZ** 2018-03-30 21:46 UTC
